"""
Django settings for cishotki project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8c5=j=g!z*_9fz&tkk_9^$8!#gs$%cog__ex0ilkzk72l_$!f0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'tshirts',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cishotki.middleware.SessionBasedLocaleMiddleware',

]

ROOT_URLCONF = 'cishotki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
                'cishotki.context_processors.theme',
            ],
            'builtins': [
                'templatetags.commontags'
            ]
        },
    },
]

WSGI_APPLICATION = 'cishotki.wsgi.application'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.AllowAllUsersModelBackend'
]

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = "/static/"


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)




MEDIA_ROOT = "/media/"

MEDIA_URL = "/media/"

SIZES = (
        ('XS', _("Extra small")),
        ('S', _("Small")),
        ('M', _("Medium")),
        ('L', _("Large")),
        ('XL', _("Extra large")),
        ('XXL', _("Extra extra large")),
    )
AUTH_USER_MODEL = 'users.User'


SEX = (
    ('m', _('Male')),
    ('f', _('Female')),
)


SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

SESSION_COOKIE_HTTPONLY = True


LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
]

DEFAULT_FROM_EMAIL = 'noreply@tour-belarus.by'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.tour-belarus.by'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'noreply@tour-belarus.by'
EMAIL_HOST_PASSWORD = '78hHp9t4'


WSB_VERSION = 2
WSB_SECRET_KEY = "Q7XUhdRUaVe6WwG9PsW9tBW49NqrvD2p"
WSB_STORE_ID = 548569367
WSB_STORE_NAME = "tour-belarus.by"
WSB_CURRENCY = "BYN"

WSB_USERNAME = "tour-belarus"
WSB_PASSWORD_MD5 = "03b440e02d1cfe7edd444c317c201f71"

WEBPAY_HOST = "https://securesandbox.webpay.by"
WEBPAY_GET_TRANSACTION_URL = "https://sandbox.webpay.by"
WSB_TEST = 1


THEME = {
    "navbar": "navbar-dark",
    "color": "343a40",
    "text": "light",
    "bg": "bg-theme-dark",
    "body": "bg-body-dark",
}


LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = "/"