# Generated by Django 2.2.4 on 2019-10-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
    ]
