# Generated by Django 2.2.6 on 2019-10-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshirt',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tshirt',
            old_name='topic',
            new_name='topics',
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images'),
        ),
    ]
