# Generated by Django 2.2.4 on 2019-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0002_auto_20191020_2036'),
        ('tshirts', '0002_remove_tshirt_size'),
    ]

    operations = [
    ]
