# Generated by Django 2.2.6 on 2019-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0005_tshirt_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='background',
            field=models.CharField(default='000000', max_length=15),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='is_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='uploaded_image',
            field=models.ImageField(default='', upload_to='uploads/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=models.ImageField(upload_to='uploads/designs'),
        ),
    ]
