# Generated by Django 2.2.6 on 2019-11-11 12:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0006_auto_20191109_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='background',
            field=models.CharField(default='#000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='uploaded_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
