# Generated by Django 2.2.6 on 2019-11-11 13:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0007_auto_20191111_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='uploaded_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
