# Generated by Django 2.2.6 on 2019-11-11 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tshirts', '0008_auto_20191111_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя и фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('cost', models.PositiveIntegerField(default=20, verbose_name='Стоимость')),
                ('count', models.PositiveIntegerField(verbose_name='Количество маек')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('seed', models.CharField(max_length=30, verbose_name='Сид')),
                ('sign', models.CharField(max_length=100, verbose_name='Подпись')),
                ('webpay_transaction_id', models.CharField(blank=True, help_text='Указан, если оплачено онлайн', max_length=100, null=True, verbose_name='ID транзакции в Webpay')),
                ('delivered', models.BooleanField(default=False, verbose_name='Явка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tshirts.TShirt', verbose_name='Майка')),
            ],
        ),
    ]
