# Generated by Django 2.2.4 on 2019-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191020_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_hash',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
