# Generated by Django 2.2.4 on 2019-10-30 22:23

from django.db import migrations, models
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191031_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_expire_datetime',
            field=models.DateTimeField(default=users.helpers.in_48_hours),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Пол'),
        ),
    ]
