# Generated by Django 2.2.4 on 2019-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191031_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_hash',
            field=models.CharField(default='', max_length=100, verbose_name='Confirmation hash'),
            preserve_default=False,
        ),
    ]
