# Generated by Django 2.2.6 on 2019-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191107_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Confirmation hash'),
        ),
    ]
